### ISSUE TITLE
[bug] Sequence freezes and never completes

### ISSUE THREAD

**Issue by terrordrummer** [Rolf-Hempel/MoonPanoramaMaker#11]
I've installed this application through the Windows Installer. FireCap plugin works well and after the initial calibration the sequence starts well and fully automated.
Randomly, the sequence gets freezed and the application do not respond anymore.
This happens with both manual and automated image capture.

Attached screenshot was taken during an automated session.
![MoonPanoramaMaker-Freezed](https://user-images.githubusercontent.com/20613850/78729252-ea58b400-7939-11ea-85ed-d19ea7fce02c.png)

System Information
![SystemInfo](https://user-images.githubusercontent.com/20613850/78729072-5be43280-7939-11ea-920f-de878b299a1d.png)

**Comment by Rolf-Hempel** [comment]
This never happened to me, also using Windows 10 Professional. I took several complte panoramas with this software last week.

The strange thing is that the GUI itself freezes. Since the GUI is running in its own thread, separated from the actual processing, this should never happen. Therefore, I would guess that it has to do with the execution environment. I noticed that your computer does not have very much RAM. You could check in the Windows Task Manager if you run out of RAM at this point. MPM itself does not need much RAM, but FireCapture (or other programs) may do.

Another thing you could do is to start the program from the Windows Command Prompt and set the MPM output parameter such that the protocol is written to stdout. It would be interesting to see if some protocol or error message is written to stdout.

You do not have to do all those tests with the real telescope. You just use the ASCOM telescope simulator.

All the best,
 Rolf

**Comment by terrordrummer** [comment]
I see, thanks for the response.
I will do a new test running your tool on another computer (a Mac with VirtualBox) and will connect to FireCapture through remotely.
I will also run in verbose mode to inspect the log messages and then I will provide a feedback.

Roberto

**Comment by terrordrummer** [comment]
Hi, during some tests I faced again the freeze, this time some logs reports the error "The remote procedure call failed".

Let me know if I can gather more logs or even a crash log in case it's saved somewhere.

Regards,

![Screen Shot 2020-04-08 at 23 39 59](https://user-images.githubusercontent.com/20613850/78836469-6d3d4580-79f2-11ea-8764-8701e9c7e193.png)

**Comment by Rolf-Hempel** [comment]
Hi,

I looked up "line 387" in "telescope.py". The program there asks the ASCOM driver for the current right ascension. Obviously this lookup fails. This means that the connection to the ASCOM driver is broken. This can have many reasons.

I recommend that you first try running MPM with POTH and the ASCOM telescope simulator. If the program does not freeze in that configuration, the problem is not related to MPM but to the ASCOM driver. If the problem persists, then it must be related to the Windows COM environment on your computer.

All the best,
 Rolf
